#!/bin/bash

volume=$(pamixer --get-volume)
prev_volume=$volume

sed -i "$ s/.*/(defvar volume-hidden \"false\")/" ~/.config/eww/volume-indicator/eww.yuck

while :
do
  sleep 0.1
   volume=$(pamixer --get-volume)

   if [ "$volume" != "$prev_volume" ]
   then
       # Звук изменился, выполняем команду для скрытия индикатора звука
       sed -i "$ s/.*/(defvar volume-hidden \"true\")/" ~/.config/eww/volume-indicator/eww.yuck
       prev_volume=$volume
       sleep 1

       # Проверяем, как долго идет изменение звука
       new_volume=$(pamixer --get-volume)
       if [ "$new_volume" != "$prev_volume" ]
       then
           # Изменение звука продолжается, ничего не делаем
           continue
       else
           # Изменение звука прекратилось, выполняем команду для отображения индикатора звука
           sed -i "$ s/.*/(defvar volume-hidden \"false\")/" ~/.config/eww/volume-indicator/eww.yuck
           prev_volume=$volume
       fi
   fi
done
